# ========================================
# EXAMPLE PYTHON TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "app"

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
NEWER_MAJOR_SEMVERSION_SEVERITY = "medium"
NEWER_MINOR_SEMVERSION_SEVERITY = "none"
NEWER_PATCH_SEMVERSION_SEVERITY = "none"
IGNORE_BELOW_SEVERITY = "low"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "medium"
REPORT_FILE = "reports/python/safety-report.json"

[semgrep]
PRINT_TIMING_INFO = false
REPORT_FILE = "reports/python/semgrep-report.json"
EXCLUDE = [
    "tests",
    "tests-integration"
]
CONFIGS = [
    "p/ci",
    "p/python",
]

[trufflehog]
SOURCE = "."
REPORT_FILE = "reports/python/truffleHog-report.json"

[python-cyclonedx]
REQUIREMENTS_FILE = "requirements.txt"
REPORT_FILE = "reports/python/python-cyclonedx-bom.json"

# ========================================
# REPORT CONFIG
# ========================================
[bom]
REPORT_FILE = "reports/python/report-cyclonedx-sbom.json"

[console]
PRINT_SUMMARY_ONLY = true

[json]
REPORT_FILE = "reports/python/eze_report.json"

[sarif]
REPORT_FILE = "reports/python/eze_report.sarif"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["python-piprot", "python-bandit", "python-safety", "python-cyclonedx", "trufflehog"]
reporters = ["console"]

[scan.linux]
tools = ["python-piprot", "python-bandit", "semgrep", "python-safety", "python-cyclonedx", "trufflehog"]
reporters = ["json", "console", "bom"]
