name: Eze Github Actions

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Preparing workflow
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
     
  test:
    needs: checkout
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    name: Eze test
    steps:
      # - name: "Running Dockerfile"
      #   uses: ./
      #   with:
      #     sarif_file: eze.sarif
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: reports/eze_report.sarif
          category: my-analysis-tool