name: Eze Github Actions

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  eze-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    name: Eze Security Test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: "Running Dockerfile"
        uses: ./
        id: eze-test
        with:
          sarif_file: eze.sarif
      - name: Write sarif to workspace file.
        run: echo ${{ steps.eze-test.outputs.eze.sarif }} >> eze.sarif
      - name: Show sarif
        run: cat eze.sarif
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: eze.sarif
          category: my-analysis-tool