name: Eze Github Action for Markdown

on:
  push: 
    branches: 
      - main


jobs:
  eze-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Eze Security Test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Testing with Eze - markdown
        uses: ./
        with: 
          upload_method: markdown
        id: eze-test
      - name: Write markdown to workspace file.
        run: |
          cat > eze.md <<'EOF'
            ${{ steps.eze-test.outputs.markdown_file }}
          EOF
          cat eze.md

      # You can ommit the following steps if you dont want to push the report into your repo. 
      - name: Commit files
        run: |
          git add eze.md && \
          git config --local user.email "eze-github-action@users.noreply.github.com" && \
          git config --local user.name "eze-action" && \
          git commit -m "Update security report" -a || \
          echo No diff

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
