name: Eze Github Actions

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  eze-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Eze Security Test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: "Generating SARIF with EZE"
        uses: ./
        with: 
          # Define the value of the upload format (sarif & markdown)
          upload_method: markdown
        id: eze-test
      - name: Write markdown to workspace file.
        run: |
          cat > eze.markdown_file <<'EOF'
            ${{ steps.eze-test.outputs.markdown_file }}
          EOF