name: Eze Github Actions Sarif

on:
  # to run on push events to the main branch
  push: {branches: main}
  # to run on pull_request events that target the main branch
  pull_request: {branches: main} 

jobs:
  eze-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    name: Eze Security Test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: "Generating SARIF with EZE"
        uses: ./
        with: 
          # Define the value of the upload format (sarif & markdown)
          upload_method: sarif
        id: eze-test
      - name: Write sarif to workspace file.
        run: |
          cat > eze.sarif <<'EOF'
            ${{ steps.eze-test.outputs.sarif_file }}
          EOF
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: eze.sarif
          category: my-analysis-tool
      - name: Print report
        run: |
          cat eze.sarif
