name: Try out

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Try print
        run: |
          echo $soy una taza
      - run: licensed status